language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.3
- 2.1.5
- 2.2.0
- 2.2.1
- 2.2.2
env:
  global:
  - secure: N9X833jLwZ1TF7oKltYmVhmIfDKXwpC+PlkaGCiEjvI7GZRr0YXLkUnPsaV/CCx4Q6UTksuivNF2OUS0oyHkjVTugGKnHEfo4+9lZ94FjIlvecPZIZ0uc3uVsqI1Fzyk8Qm1z7CWqSlucIIZh8sgq8EitAf4oynzfVeMntub4xw=
  - secure: SranIG7W1U1uBQPMnunL9bNoKz8rQmvinHV9KxJEJJ/VA6GoPEwcjd1YERraBbmDm4HFyfxwMD0APb9n3Nk1OD23GFkRbpW/C740cj7nvdxNU1YeTqc0vBRGqZLan0UtB0tvjf0aO5hoyEHrmoS49SSdO4vPfOkoWIRSdSs5gMg=
  - secure: QHuuEO1av9qbuUpwrZQ+uBYFuxBca3O5+smR2fWNzrlcZfG+3ghNRRcwD2UEqQ2UU/sLYyOmb7YoDaEvwRnyADVj6DtzOoDch/2P4Ofi3O3pdWDxmDNkb0WW70LK7uTILPoM5L1BkHx5hs077SB10m6jaEuxKbg56DcTiHap9CY=
deploy:
  provider: rubygems
  gem: factor-connector-mailgun
  api_key:
    secure: mMY5ZBtkbojnbXBLCnMpvdokLoJU+RbeafrQ3CZpOGXK4+mg8hoY79kdNIYNImF4bhOh3G0Ol0ByCsBGcciX1hknWLyrv8ZNNxlhoDLgTozcTIi8Zyd1SkRD360LUxGn5cDOgX+7o226zh6p2B742dVcgIf8Y469cGxT855DpBg=
  on:
    tags: true
    all_branches: true
